# This file describes temperature pressure and humidity values as provided by
# the temperature probe from KRex2
name: KRex2.TPH
class: xgds_braille_app.Environmental
superclass: xgds_timeseries.TimeSeriesModel
extension: tsv
delimiter: "\t"
flight_required: true
fields:
  timestamp:
    type: unixtime_int_microsecond
  temperature:
    type: float
    min: 0
    max: 45
    units: C
    label: Temp
  pressure:
    type : float
  humidity:
    type : float
    min : 0
    max : 100
